# Generated by Django 5.2.4 on 2025-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metric_metricvalue_remove_bodymeasurement_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='metric_id',
            field=models.CharField(blank=True, help_text="Unique alphanumeric ID for use in formulas (e.g., 'WEIGHT', 'HEIGHT', 'BF_PCT')", max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='measurement_type',
            field=models.CharField(choices=[('baseline', 'Baseline'), ('target', 'Target'), ('current', 'Current'), ('log', 'Log'), ('goal', 'Goal'), ('calculated', 'Calculated')], default='log', max_length=20),
        ),
    ]
