# Generated by Django 5.2.4 on 2025-08-17 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_metric_metric_id_alter_metricvalue_measurement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetricFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'metric')},
            },
        ),
        migrations.AddField(
            model_name='metric',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_metrics', through='metrics.UserMetricFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
