# Generated by Django 5.2.4 on 2025-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_usermetricfavorite_metric_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcalculator",
            name="age_years",
            field=models.IntegerField(
                blank=True, help_text="Age in years (for BMR calculation)", null=True
            ),
        ),
    ]
