# Generated by Django 5.2.4 on 2025-08-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_category_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
