# Generated by Django 5.2.4 on 2025-08-13 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_diet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meal',
            name='duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='meal',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='last_synced_to_calendar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('regular', 'Regular Meal'), ('cheat', 'Cheat Meal'), ('refeed', 'Refeed Meal'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout'), ('snack', 'Snack')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='meal',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
