# Generated by Django 5.2.4 on 2025-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_diet_end_date_diet_notes_diet_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'No Recurrence'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekday', 'Weekdays (Mon-Fri)'), ('weekend', 'Weekends (Sat-Sun)'), ('custom', 'Custom')], default='none', max_length=10),
        ),
    ]
