# Generated by Django 5.2.4 on 2025-08-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_alter_meal_recurrence_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date for recurrent meals", null=True
            ),
        ),
    ]
