# Generated by Django 5.2.4 on 2025-08-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_meal_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealrecord",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="carbs",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="fats",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="meal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="proteins",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mealrecord",
            name="quantity_grams",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mealrecord",
            name="meal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meals.meal",
            ),
        ),
    ]
