# Generated by Django 5.2.4 on 2025-08-15 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0008_mealrecord_calories_mealrecord_carbs_mealrecord_fats_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="is_personal",
            field=models.BooleanField(
                default=False, help_text="Personal ingredient created by user"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
