# Generated by Django 5.2.4 on 2025-08-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
