# Generated by Django 5.2.4 on 2025-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="provider",
            field=models.CharField(
                choices=[
                    ("telegram", "Telegram"),
                    ("whatsapp", "WhatsApp"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter"),
                ],
                default="telegram",
                max_length=255,
            ),
        ),
    ]
