# Generated by Django 5.2.4 on 2025-07-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_usercontext_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercontext",
            name="provider",
        ),
    ]
