# Generated by Django 5.2.4 on 2025-08-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "calories_per_hour_per_kg",
                    models.FloatField(
                        help_text="Calories burned per hour per kg of body weight"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='Category like "Cardio", "Strength", "Work"',
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Pre-defined activity types that come with the system",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this activity type (null for system defaults)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activities_activity_type",
                "ordering": ["category", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(help_text="Actual duration in hours"),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activitytype",
                    ),
                ),
            ],
            options={
                "db_table": "activities_activity_record",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(help_text="Planned duration in hours"),
                ),
                ("date", models.DateField()),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this planned activity was completed",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.activitytype",
                    ),
                ),
            ],
            options={
                "db_table": "activities_activity",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
