# Generated by Django 5.2.4 on 2025-08-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='Category like "Cardio", "Strength", "Flexibility"',
                        max_length=100,
                    ),
                ),
                (
                    "muscle_groups",
                    models.CharField(
                        blank=True,
                        help_text="Primary muscle groups targeted",
                        max_length=200,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "equipment_needed",
                    models.CharField(
                        blank=True,
                        help_text="Equipment required for this exercise",
                        max_length=200,
                    ),
                ),
                (
                    "calories_per_hour_per_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Calories burned per hour per kg of body weight",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_personal",
                    models.BooleanField(
                        default=False, help_text="Personal exercise created by user"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this exercise (null for system defaults)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activities_exercise",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        help_text="Duration in minutes for this exercise"
                    ),
                ),
                ("sets", models.IntegerField(default=1, help_text="Number of sets")),
                (
                    "reps",
                    models.IntegerField(
                        blank=True, help_text="Number of repetitions per set", null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Weight in kg (for strength training)",
                        null=True,
                    ),
                ),
                (
                    "distance_km",
                    models.FloatField(
                        blank=True, help_text="Distance in km (for cardio)", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of exercises in the activity"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="activities.activity",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "activities_activity_exercise",
                "ordering": ["order", "id"],
            },
        ),
    ]
