# Generated by Django 5.2.4 on 2025-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_exercise_activityexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityexercise",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible JSON data for exercise-specific details",
            ),
        ),
    ]
