# Generated by Django 5.2.4 on 2025-08-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_activityexercise_details"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityexercise",
            name="distance_km",
        ),
        migrations.RemoveField(
            model_name="activityexercise",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="activityexercise",
            name="reps",
        ),
        migrations.RemoveField(
            model_name="activityexercise",
            name="sets",
        ),
        migrations.RemoveField(
            model_name="activityexercise",
            name="weight_kg",
        ),
        migrations.RemoveField(
            model_name="activitytype",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="activitytype",
            name="exercise_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON Schema for exercise details in this activity type",
            ),
        ),
        migrations.AlterField(
            model_name="activityexercise",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Exercise-specific data according to activity type schema",
            ),
        ),
        migrations.AlterField(
            model_name="activityexercise",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Free-form notes about this exercise", null=True
            ),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="category",
            field=models.CharField(
                choices=[
                    ("cardio", "Cardio"),
                    ("strength", "Strength"),
                    ("flexibility", "Flexibility"),
                    ("sports", "Sports"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="display_name",
            field=models.CharField(
                help_text='User-friendly name (e.g., "Running")', max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="name",
            field=models.CharField(
                help_text='Internal name (e.g., "running")', max_length=100, unique=True
            ),
        ),
    ]
