# Generated by Django 5.2.4 on 2025-08-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_remove_activityexercise_distance_km_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["-start_date", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="activity",
            name="date",
        ),
        migrations.RemoveField(
            model_name="activityrecord",
            name="activity_type",
        ),
        migrations.AddField(
            model_name="activity",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="End date for recurrent activities", null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="last_synced_to_calendar",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Custom name for this activity",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "No Recurrence"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("weekday", "Weekdays (Mon-Fri)"),
                    ("weekend", "Weekends (Sat-Sun)"),
                    ("custom", "Custom"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="recurrence_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="activity_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="activity_type_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="activityrecord",
            name="duration_hours",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
