# Generated by Django 5.2.4 on 2025-08-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_alter_activity_options_remove_activity_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="recurrence_days",
            field=models.CharField(
                blank=True,
                help_text='Comma-separated days for custom recurrence (e.g., "mon,tue,thu,fri")',
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "No Recurrence"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("weekday", "Weekdays (Mon-Fri)"),
                    ("weekend", "Weekends (Sat-Sun)"),
                    ("custom", "Custom Days"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
