# Generated by Django 5.2.4 on 2025-07-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_bodymeasurement_goal_bodymeasurement_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='measurement_type',
            field=models.CharField(choices=[('target', 'Target'), ('baseline', 'Baseline'), ('log', 'Log')], max_length=50),
        ),
    ]
