# Generated by Django 5.2.4 on 2025-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_alter_bodymeasurement_measurement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasurement",
            name="metric",
            field=models.CharField(
                choices=[
                    ("age_years", "Age (years)"),
                    ("gender", "Gender"),
                    ("height_cm", "Height (cm)"),
                    ("weight_kg", "Weight (kg)"),
                    ("waist_cm", "Waist (cm)"),
                    ("hip_cm", "Hip (cm)"),
                    ("neck_cm", "Neck (cm)"),
                    ("arm_circumference_cm", "Arm Circumference (cm)"),
                    ("thigh_circumference_cm", "Thigh Circumference (cm)"),
                    ("calf_circumference_cm", "Calf Circumference (cm)"),
                    ("body_fat_percentage", "Body Fat (%)"),
                    ("muscle_mass_percentage", "Muscle Mass (%)"),
                    ("bmi_value", "BMI Value"),
                ],
                default="weight_kg",
                max_length=50,
            ),
        ),
    ]
